#!/bin/bash

set -e

$INPUT_ARTIFACTS_DIR/weak/wrapper_generator.release/strong/wrapper_generator.release/bin/wrapper_generator $INPUT_ARTIFACTS_DIR/weak/link_checker.main/strong $OUTPUT_ARTIFACTS_DIR \
    link_checker qbt.fringe.link_checker.Main \

